/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

int main() {
  const int N = 4000000;

  int sum = 0;
  int i = 0;
  int j = 1;
  int k;

  while (j < N) {
    k = i + j;
    i = j;
    j = k;
    if (j % 2 == 0)
      sum += j;
  }
  int answer = sum;

  std::cout << answer << '\n';
  
  return 0;
}

// Answer: 4613732
// Time: 0m0.003s
