"""Triangle, pentagonal, and hexagonal numbers are
generated by the following formulae:

Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
import math


def is_pentagonal(n):
    """Checks if a number is pentagonal or not.
    
    Information
    ===========
    Pentagonal numbers can be generated by the following formula:
    Pn = n(3n-1)/2

    The most efficient way to determine if a particular number is pentagonal
    is by plugging it into the following formula:

    n = (1 + sqrt(24x+1)) / 6

    If n is a natural number, then the number is pentagonal.
    """
    if (1 + (24*n + 1)**0.5) % 6 == 0:
        return True

    return False


def is_hexagonal(n):
    """Checks if a number is hexagonal or not.
    
    Information
    ===========
    Hexagonal numbers can be generated by the following formula:

    Hn = n(2n−1)

    The most efficient way to determine if a particular number is hexagonal
    is by plugging it into the following formula:

    n = (1 + sqrt(8x+1)) / 4

    If n is a natural number, then the number is pentagonal.
    """
    print((1 + (8*n + 1)**0.5) % 4)
    if (1 + (8*n + 1)**0.5) % 4 == 0:
        return True
    
    return False

n = 40755
answer = 0

while answer == 0:
    t = n*(n+1)/2 
    print(n)

    if is_hexagonal(t) and is_pentagonal(t):
        answer = int(t)
        print(answer)

    n += 1