"""Pentagonal numbers are generated by the formula, Pn = n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk − Pj| is minimised;
what is the value of D?
"""
def is_pentagonal(n):
    """Checks if a number is pentagonal or not.
    
    Information
    ===========
    Pentagonal numbers can be generated by the following formula:
    Pn = n(3n-1)/2

    The most efficient way to determine if a particular number is pentagonal
    is by plugging it into the following formula:

    n = (1 + sqrt(24x+1)) / 6

    If n is a natural number, then the number is pentagonal.
    """
    if (1 + (24*n + 1)**0.5) % 6 == 0:
        return True

    return False



found = False
i = 1

while not found:
    for j in range(1, i):
        a = i*(3*i-1)/2
        b = j*(3*j-1)/2
        if is_pentagonal(a+b) and is_pentagonal(a-b):
            found = True
            answer = a-b
            print(answer)
    i += 1


# Answer: 5482660
# Time: 0m1.850s
