# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn = n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn = n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn = n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.


i = 285 + 1
j = 165 + 1
k = 143 + 1


pents = []
hexes = []

loop do
  x = i * (i + 1) / 2
  y = j * ((3*j) - 1) / 2
  pents << y
  z = k * ((2*k) - 1)
  hexes << z

  if pents.include?(x) && hexes.include?(x)
    puts "The triangle you're looking for is #{x}. Its indices are T-#{i}, P-#{j}, H-#{k}."
    break
  end

  i += 1
  j += 1
  k += 1
end

# Complete!
# Answer = 1533776805
